In [ ]:
import numpy  as np
zeros = np.zeros((10,))
print (zeros)

In [37]:
vowels = np.array(list('aeiou'))
print (vowels)

['a' 'e' 'i' 'o' 'u']


In [23]:
ones =np.ones ((2,5),dtype=int)
print(ones )

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
myarray1  =np.array([[2.7,  -2,  -19],[0,  3.4,  99.9],[10.6,  0,  13]])
print (myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [19]:
myarray2 = np.arange(start=4, stop=64, step=4, dtype=float) 

myarray2 = myarray2.reshape((3,5))
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


In [23]:
print("Array is of type: ", type(myarray1))

Array is of type:  <class 'numpy.ndarray'>


In [24]:
print("No. of dimensions: ", myarray1.ndim)

No. of dimensions:  2


In [67]:
print("No. of dimensions: ", myarray1.ndim , myarray2.ndim ,zeros.ndim,vowels.ndim)

No. of dimensions:  2 2 1 1


In [73]:
print("Shape of myarray1: ", myarray1.shape ,
      "Shape of myarray2: ", myarray2.shape ,
     "Shape of zeros: " , zeros.shape ,
     "Shape of vowels: " , vowels.shape)

Shape of myarray1:  (3, 5) Shape of myarray2:  (3, 5) Shape of zeros:  (10,) Shape of vowels:  (5,)


In [107]:
print("Size of myarray1: ", myarray1.size,
      "Size of myarray2: ", myarray2.size,
     "Size of zeros: ", zeros.size,
      "Size of vowels: ", vowels.size,
      "Size of ones: ", ones.size)

Size of myarray1:  15 Size of myarray2:  15 Size of zeros:  10 Size of vowels:  5 Size of ones:  10


In [109]:
print("myArray1 stores elements of type: ", myarray1.dtype,
      "myarray2 stores elements of type: ", myarray2.dtype,
      "zeros stores elements of type: ", zeros.dtype,
      "vowels stores elements of type: ", vowels.dtype,
      "ones stores elements of type: ", ones.dtype)
    

myArray1 stores elements of type:  float64 myarray2 stores elements of type:  float64 zeros stores elements of type:  float64 vowels stores elements of type:  <U1 ones stores elements of type:  int32


In [61]:
print("Array is of type: ", type(vowels))

Array is of type:  <class 'numpy.ndarray'>


In [88]:
myarr1 = myarray1.itemsize
print(myarr1)


8


In [84]:
myarr2 = myarray2.itemsize
print(myarr2)

8


In [89]:
vowels = vowels.itemsize
print(vowels)

4


In [93]:
one = ones.itemsize
print(one)

4


In [100]:
z= zeros.itemsize
print(z)


8


In [112]:
ones.reshape(10)  

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [114]:
print(vowels[2])

i


In [7]:
print(vowels[3])

o


In [7]:
myarray1[[1,2]]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [10]:
myarray1[ :0]

array([], shape=(0, 3), dtype=float64)

In [11]:
myarray1[[0]]

array([[  2.7,  -2. , -19. ]])

In [13]:
myarray1[: : -1]

array([[ 10.6,   0. ,  13. ],
       [  0. ,   3.4,  99.9],
       [  2.7,  -2. , -19. ]])

In [24]:
divisor=3
out=np.divide(ones,divisor)
print(out)

[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]


In [20]:
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E=np.array_split(myarray2,5,axis=1)
print(myarray2A,myarray2B,myarray2C,myarray2D,myarray2E)

[[ 4.]
 [24.]
 [44.]] [[ 8.]
 [28.]
 [48.]] [[12.]
 [32.]
 [52.]] [[16.]
 [36.]
 [56.]] [[20.]
 [40.]
 [60.]]


In [26]:
myarray2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(myarray2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
myarray1+myarray2

array([[  1. ,   0. , -16. ],
       [  6.7,   5. ,  19. ],
       [ 17.6,  11.4, 108.9]])

In [28]:
newarray=myarray1-myarray2
print(newarray)

[[ -1.   -4.  -22. ]
 [ -1.3  -5.    7. ]
 [  3.6  -4.6  90.9]]


In [29]:
myarray2*myarray1

array([[  0. ,  -4. , -57. ],
       [ 10.8,   0. ,  78. ],
       [ 74.2,  27.2, 899.1]])

In [30]:
myarray3=myarray1@myarray2
print(myarray3)

[[-141.  -162.  -183. ]
 [  93.7  109.4  125.1]
 [ 723.5  837.4  951.3]]


In [31]:
myarray1/myarray2

array([[ 0.        , -1.        , -6.33333333],
       [ 0.675     ,  0.        ,  2.16666667],
       [ 1.51428571,  0.425     , 11.1       ]])

In [32]:
myarray1**3/2

array([[ 0.000000e+00, -4.000000e+00, -3.429500e+03],
       [ 9.841500e+00,  0.000000e+00,  1.098500e+03],
       [ 5.955080e+02,  1.965200e+01,  4.985015e+05]])

In [34]:
np.around(myarray2**(1/2)/2,2)

array([[0.5 , 0.71, 0.87],
       [1.  , 1.12, 1.22],
       [1.32, 1.41, 1.5 ]])

In [35]:
ones.transpose()
myarray2.transpose

<function ndarray.transpose>

In [38]:
(np.sort(vowels))[ : : -1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [39]:
myarray1.sort(axis=0)

In [40]:
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E=np.array_split(myarray2,5,axis=1)
print(myarray2A,myarray2B,myarray2C,myarray2D,myarray2E)

[[1]
 [4]
 [7]] [[2]
 [5]
 [8]] [[3]
 [6]
 [9]] [] []


In [41]:
(np.array([myarray2A,myarray2B,myarray2C])).reshape(3,3)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
myarray4=np.arange(-1,9.5,0.25)
a1,a2,a3=np.array_split(myarray4,3,axis=0)

In [44]:
myarray4.sum()

173.25

In [45]:
myarray4.max()

9.25

In [46]:
myarray4.min()

-1.0

In [47]:
myarray4.std(axis=0)

3.0302296392627848

In [48]:
myarray4.mean(axis=0)

4.125