In [2]:
import numpy as np

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
print(x)

[[1 2 3]
 [4 5 6]]


In [5]:
type(x)

numpy.ndarray

In [6]:
x.shape

(2, 3)

In [7]:
x.dtype

dtype('int32')

In [10]:
np.zeros(5),np.ones(5)

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [23]:
import numpy as np
 
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
  
print(np.reshape(a, (3, 3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print('flattening a...')
print(a.flatten())

flattening a...
[1 2 3 4 5 6 7 8 9]


In [14]:
test_str = 'RVRJC'
  
print("The original string is : " + str(test_str))
res = ''
for ele in test_str:
    res  += ele + "\n" 
print("The converted string : " + str(res)) 

The original string is : RVRJC
The converted string : R
V
R
J
C



In [20]:
test_str = 'R\nV\nR\nJ\nC\n'
print("The original string is : " + str(test_str))
res = test_str.replace("\n", "")
print("The converted string : " + str(res))

The original string is : R
V
R
J
C

The converted string : RVRJC


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
print(arr[0])


1


In [26]:
a = np.array([[1,7,6],[9,4,4],[3,4,8]]) 
print (a)   
print (np.amin(a,1))
print (np.amin(a,0))
print (np.amax(a)) 
print (np.amax(a, axis = 0))

[[1 7 6]
 [9 4 4]
 [3 4 8]]
[1 4 3]
[1 4 4]
9
[9 7 8]
